sudo: required
language: generic

services: 
 - docker 

before_install:
  - docker build -t seyithanalkan/docker-react -f Dockerfile.dev .

script :
  - docker run -e CI=true seyithanalkan/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker2"
  env: "Docker2-env"
  bucket_name: "elasticbeanstalk-eu-west-1-544167776152"
  bucket_path: "docker2"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  edge: true 
  skip_cleanup: true